//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public string MaCTPN { get; set; }
        public string MaPhieuNhap { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
    
        public virtual PhieuNhapDichVu PhieuNhapDichVu { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
