//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string MaDanhGia { get; set; }
        public Nullable<int> MaUser { get; set; }
        public string MaSan { get; set; }
        public Nullable<int> Diem { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual SanTheThao SanTheThao { get; set; }
        public virtual TaiKhoanUser TaiKhoanUser { get; set; }
    }
}
