//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatSan()
        {
            this.ChiTietDichVu = new HashSet<ChiTietDichVu>();
            this.ThanhToan = new HashSet<ThanhToan>();
            this.Voucher = new HashSet<Voucher>();
        }
    
        public string MaDat { get; set; }
        public Nullable<int> MaUser { get; set; }
        public string MaSan { get; set; }
        public System.DateTime NgayDat { get; set; }
        public string MaKhung { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDichVu> ChiTietDichVu { get; set; }
        public virtual KhungGio KhungGio { get; set; }
        public virtual SanTheThao SanTheThao { get; set; }
        public virtual TaiKhoanUser TaiKhoanUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Voucher { get; set; }
    }
}
