//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoNguoiChoi
    {
        public int MaUser { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> SoTranThamGia { get; set; }
        public Nullable<int> SoTranThang { get; set; }
        public Nullable<int> DiemUyTin { get; set; }
        public string GioiThieu { get; set; }
    
        public virtual TaiKhoanUser TaiKhoanUser { get; set; }
    }
}
