//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuTheThao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuTheThao()
        {
            this.SanTheThao = new HashSet<SanTheThao>();
        }
    
        public string MaKhu { get; set; }
        public string MaDoiTac { get; set; }
        public string TenKhu { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<System.TimeSpan> GioMoCua { get; set; }
        public Nullable<System.TimeSpan> GioDongCua { get; set; }
        public string MoTa { get; set; }
        public string KhuVucHienThi { get; set; }
    
        public virtual DoiTac DoiTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanTheThao> SanTheThao { get; set; }
    }
}
