//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrongSan
    {
        public string MaSan { get; set; }
        public System.DateTime Ngay { get; set; }
        public string MaKhung { get; set; }
        public string TrangThai { get; set; }
    
        public virtual KhungGio KhungGio { get; set; }
        public virtual SanTheThao SanTheThao { get; set; }
    }
}
