//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiThamGiaTran
    {
        public string MaTran { get; set; }
        public int MaUser { get; set; }
        public string TrangThai { get; set; }
    
        public virtual TranDau TranDau { get; set; }
        public virtual TaiKhoanUser TaiKhoanUser { get; set; }
    }
}
