//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_SAN_THE_THAOEntities : DbContext
    {
        public QL_SAN_THE_THAOEntities()
            : base("name=QL_SAN_THE_THAOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoTri> BaoTri { get; set; }
        public virtual DbSet<ChiTietDichVu> ChiTietDichVu { get; set; }
        public virtual DbSet<DanhGia> DanhGia { get; set; }
        public virtual DbSet<DatSan> DatSan { get; set; }
        public virtual DbSet<DichVu> DichVu { get; set; }
        public virtual DbSet<DoiTac> DoiTac { get; set; }
        public virtual DbSet<HoSoNguoiChoi> HoSoNguoiChoi { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<KhungGio> KhungGio { get; set; }
        public virtual DbSet<KhuTheThao> KhuTheThao { get; set; }
        public virtual DbSet<LichTrongSan> LichTrongSan { get; set; }
        public virtual DbSet<LoaiTheThao> LoaiTheThao { get; set; }
        public virtual DbSet<NguoiThamGiaTran> NguoiThamGiaTran { get; set; }
        public virtual DbSet<SanTheThao> SanTheThao { get; set; }
        public virtual DbSet<TaiKhoanUser> TaiKhoanUser { get; set; }
        public virtual DbSet<TinTuc> TinTuc { get; set; }
        public virtual DbSet<ThanhToan> ThanhToan { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<TranDau> TranDau { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
        public virtual DbSet<PhieuNhapDichVu> PhieuNhapDichVu { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; }
    
        public virtual int PROC_TaoDatSan(string maUser, string maSan, string maKhung, Nullable<System.DateTime> ngayDat)
        {
            var maUserParameter = maUser != null ?
                new ObjectParameter("MaUser", maUser) :
                new ObjectParameter("MaUser", typeof(string));
    
            var maSanParameter = maSan != null ?
                new ObjectParameter("MaSan", maSan) :
                new ObjectParameter("MaSan", typeof(string));
    
            var maKhungParameter = maKhung != null ?
                new ObjectParameter("MaKhung", maKhung) :
                new ObjectParameter("MaKhung", typeof(string));
    
            var ngayDatParameter = ngayDat.HasValue ?
                new ObjectParameter("NgayDat", ngayDat) :
                new ObjectParameter("NgayDat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TaoDatSan", maUserParameter, maSanParameter, maKhungParameter, ngayDatParameter);
        }
    
        public virtual int PROC_TaoTranDau(string maSan, string maLoai, string maNguoiToChuc, Nullable<System.DateTime> ngay, string maKhung, string tenTran, string moTa, Nullable<int> soNguoi)
        {
            var maSanParameter = maSan != null ?
                new ObjectParameter("MaSan", maSan) :
                new ObjectParameter("MaSan", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var maNguoiToChucParameter = maNguoiToChuc != null ?
                new ObjectParameter("MaNguoiToChuc", maNguoiToChuc) :
                new ObjectParameter("MaNguoiToChuc", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            var maKhungParameter = maKhung != null ?
                new ObjectParameter("MaKhung", maKhung) :
                new ObjectParameter("MaKhung", typeof(string));
    
            var tenTranParameter = tenTran != null ?
                new ObjectParameter("TenTran", tenTran) :
                new ObjectParameter("TenTran", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var soNguoiParameter = soNguoi.HasValue ?
                new ObjectParameter("SoNguoi", soNguoi) :
                new ObjectParameter("SoNguoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TaoTranDau", maSanParameter, maLoaiParameter, maNguoiToChucParameter, ngayParameter, maKhungParameter, tenTranParameter, moTaParameter, soNguoiParameter);
        }
    
        public virtual int PROC_XacNhanThanhToan(string maDat, string phuongThuc)
        {
            var maDatParameter = maDat != null ?
                new ObjectParameter("MaDat", maDat) :
                new ObjectParameter("MaDat", typeof(string));
    
            var phuongThucParameter = phuongThuc != null ?
                new ObjectParameter("PhuongThuc", phuongThuc) :
                new ObjectParameter("PhuongThuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_XacNhanThanhToan", maDatParameter, phuongThucParameter);
        }
    }
}
