//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanTheThao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanTheThao()
        {
            this.BaoTri = new HashSet<BaoTri>();
            this.DanhGia = new HashSet<DanhGia>();
            this.DatSan = new HashSet<DatSan>();
            this.LichTrongSan = new HashSet<LichTrongSan>();
            this.TranDau = new HashSet<TranDau>();
        }
    
        public string MaSan { get; set; }
        public string MaKhu { get; set; }
        public string MaLoai { get; set; }
        public string TenSan { get; set; }
        public Nullable<decimal> GiaThueTheoGio { get; set; }
        public string TrangThai { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> IsNoiBat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoTri> BaoTri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatSan> DatSan { get; set; }
        public virtual KhuTheThao KhuTheThao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrongSan> LichTrongSan { get; set; }
        public virtual LoaiTheThao LoaiTheThao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranDau> TranDau { get; set; }
    }
}
