//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.LoaiTheThao = new HashSet<LoaiTheThao>();
        }
    
        public int TrainerId { get; set; }
        public string HoTen { get; set; }
        public string MoTaNgan { get; set; }
        public string KhuVuc { get; set; }
        public string AnhDaiDienUrl { get; set; }
        public Nullable<decimal> SoSaoDanhGia { get; set; }
        public Nullable<decimal> GiaMoiBuoi { get; set; }
        public Nullable<int> SoNamKinhNghiem { get; set; }
        public string ChungChi { get; set; }
        public Nullable<bool> IsAcademy { get; set; }
        public string AgeGroup { get; set; }
        public string Services { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiTheThao> LoaiTheThao { get; set; }
    }
}
