//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TranDau()
        {
            this.NguoiThamGiaTran = new HashSet<NguoiThamGiaTran>();
        }
    
        public string MaTran { get; set; }
        public string MaSan { get; set; }
        public string MaLoai { get; set; }
        public Nullable<int> MaNguoiToChuc { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaKhung { get; set; }
        public string TenTran { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoNguoiToiDa { get; set; }
        public string TrangThai { get; set; }
        public string LoaiHinh_Tran { get; set; }
        public string TrinhDo { get; set; }
    
        public virtual KhungGio KhungGio { get; set; }
        public virtual LoaiTheThao LoaiTheThao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiThamGiaTran> NguoiThamGiaTran { get; set; }
        public virtual SanTheThao SanTheThao { get; set; }
        public virtual TaiKhoanUser TaiKhoanUser { get; set; }
    }
}
